<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
const props=defineProps({reviews:{type:Array,default:()=>[]}})
const active=ref(0)
const review=computed(()=>props.reviews[active.value]||{})
let rotationTimer
const select=step=>{active.value=(active.value+step+props.reviews.length)%props.reviews.length}
const startRotation=(delay=3000)=>{window.clearInterval(rotationTimer);rotationTimer=window.setInterval(()=>select(1),delay)}
const navigate=step=>{select(step);startRotation(5000)}
onMounted(()=>startRotation())
onBeforeUnmount(()=>window.clearInterval(rotationTimer))
</script>
<template><section id="reviews" class="section reviews"><div class="wrap"><div class="reviews-heading"><div><p class="eyebrow">Customer reviews</p><h2>Don't take our word for it.</h2><p class="muted">Real people. Real RAWR experiences.</p></div><div class="review-controls"><button aria-label="Previous review" @click="navigate(-1)">←</button><span>{{String(active+1).padStart(2,'0')}} / {{String(reviews.length).padStart(2,'0')}}</span><button aria-label="Next review" @click="navigate(1)">→</button></div></div><div class="review-stage"><div class="review-orbit" :style="{'--orbit-turn':`${active*120}deg`}" aria-hidden="true"><i></i><i></i><i></i><b><br></b></div><article class="featured-card"><span class="stars">★★★★★</span><blockquote>“{{review.quote}}”</blockquote><div class="reviewer"><span>{{review.name?.slice(0,1)}}</span><p><b>{{review.name}}</b><small>{{review.role}}</small></p></div></article></div></div></section></template>
<style scoped>.reviews{overflow:hidden;background:#f15a24;color:#111}.reviews .eyebrow{color:#111}.reviews-heading{display:flex;justify-content:space-between;align-items:end;gap:30px}.review-controls{display:flex;align-items:center;gap:16px;padding-bottom:8px;font-size:.75rem;font-weight:800;letter-spacing:.12em}.review-controls button{width:47px;height:47px;border:1px solid #171719;border-radius:50%;background:transparent;color:#171719;font-size:1.35rem;cursor:pointer;transition:background .2s,color .2s,transform .2s}.review-controls button:hover{background:#171719;color:#f15a24;transform:scale(1.08)}.review-stage{position:relative;display:grid;justify-items:center;min-height:350px;margin-top:42px}.featured-card{position:relative;z-index:2;width:min(620px,calc(100% - 190px));min-height:260px;padding:42px 48px;background:#171719;color:#f6f6f6;display:flex;flex-direction:column;transition:transform .25s ease,box-shadow .25s ease}.featured-card:hover{transform:scale(1.035);box-shadow:0 24px 45px rgba(0,0,0,.26)}.stars{color:#f15a24;letter-spacing:4px}.featured-card blockquote{margin:26px 0;font-size:clamp(1.25rem,2vw,1.7rem);line-height:1.42;letter-spacing:-.03em}.reviewer{display:flex;align-items:center;gap:12px;margin-top:auto}.reviewer>span{display:grid;place-items:center;width:37px;height:37px;border-radius:50%;background:#f15a24;color:#171719;font-weight:900}.reviewer p{display:grid;gap:3px;margin:0;font-size:.86rem}.reviewer small{color:#aaa}.review-orbit{position:absolute;right:5%;top:-48px;width:295px;height:295px;border:1px solid rgba(23,23,23,.48);border-radius:50%;transform:rotate(var(--orbit-turn));transition:transform .55s cubic-bezier(.2,.8,.2,1)}.review-orbit:before,.review-orbit:after{content:'';position:absolute;inset:20px;border:1px solid rgba(23,23,23,.19);border-radius:50%}.review-orbit:after{inset:49px}.review-orbit i{position:absolute;z-index:1;width:13px;height:13px;border-radius:50%;background:#171719}.review-orbit i:nth-child(1){top:-7px;left:50%}.review-orbit i:nth-child(2){right:20px;bottom:35px;background:#fff}.review-orbit i:nth-child(3){left:32px;bottom:22px}.review-orbit b{position:absolute;inset:0;display:grid;place-content:center;text-align:center;font-size:1rem;line-height:.9;letter-spacing:.08em;text-transform:uppercase;transform:rotate(calc(var(--orbit-turn) * -1));transition:transform .55s cubic-bezier(.2,.8,.2,1)}@media(max-width:760px){.reviews-heading{align-items:start;flex-direction:column}.review-stage{min-height:330px;margin-top:30px}.featured-card{width:calc(100% - 24px);padding:34px 30px}.review-orbit{right:-105px;top:-68px;width:245px;height:245px;opacity:.6}.review-controls{padding-bottom:0}.featured-card:hover{transform:scale(1.015)}}@media(prefers-reduced-motion:reduce){.review-orbit,.review-orbit b,.featured-card{transition:none}}</style>
