<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import logo from '../../../assets/desktop/rawr-logo.png'
defineProps({page:String,cartCount:Number,signedIn:Boolean})
const emit=defineEmits(['navigate','logout']),links=[['home','HOME'],['shop','SHOP'],['ingredients','INGREDIENTS'],['about','ABOUT'],['reviews','REVIEWS'],['contact','CONTACT']],accountOpen=ref(false),menuOpen=ref(false),accountControl=ref(null)
const account=()=>{if(!accountOpen.value) accountOpen.value=true}
const closeOnOutsideClick=event=>{if(accountControl.value&&!accountControl.value.contains(event.target))accountOpen.value=false}
const navigate=id=>{menuOpen.value=false;emit('navigate',id)}
onMounted(()=>document.addEventListener('click',closeOnOutsideClick))
onBeforeUnmount(()=>document.removeEventListener('click',closeOnOutsideClick))
</script>
<template><header><div class="wrap nav"><button class="nav-links-toggle nav-icon" :aria-expanded="menuOpen" aria-label="Open navigation menu" @click="menuOpen=!menuOpen"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M5 9h22M5 16h22M5 23h22"/></svg></button><button class="brand" @click="navigate('home')"><img :src="logo" alt="RAWR"></button><nav><div class="nav-links" :class="{open:menuOpen}"><button v-for="[id,label] in links" :key="id" :class="{active:page===id}" @click="navigate(id)">{{label}}</button></div><button class="nav-icon cart-button" :class="{active:page==='cart'}" aria-label="Cart" @click="navigate('cart')"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M2 4h4l3.2 16.2h15.4l3.4-11.3H8.1"/><circle cx="12" cy="26" r="1.8"/><circle cx="24" cy="26" r="1.8"/></svg><i v-if="cartCount">{{cartCount}}</i></button><div ref="accountControl" class="account-control"><button class="nav-icon" :class="{active:page==='account'}" :aria-expanded="accountOpen" aria-label="Account" @click="signedIn?account():navigate('account')"><svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="10" r="5"/><path d="M6 28c1.1-6 4.6-9 10-9s8.9 3 10 9"/></svg></button><div v-if="signedIn&&accountOpen" class="account-menu"><button @click="accountOpen=false;navigate('account')">Order history</button><button @click="accountOpen=false;emit('logout')">Log out</button></div></div></nav></div></header></template>
<style scoped>header{position:sticky;top:0;z-index:20;border-bottom:1px solid #2b2b2d;background:#090909}.nav{width:min(1280px,calc(100% - 32px));height:65px;display:flex;align-items:center;gap:16px}.brand{border:0;background:none;padding:0;display:flex;align-items:center}.brand img{display:block;width:100px;height:auto}nav{margin-left:auto;display:flex;align-items:center;gap:14px;height:100%}.nav-links{display:flex;align-items:center;gap:14px;height:100%}.nav-links button{position:relative;background:none;border:0;color:#d0d0d0;font-size:.83rem;letter-spacing:.1em;font-weight:800;cursor:pointer;padding:0;height:100%}.nav-links button:hover,.nav-links button.active{color:#fff}.nav-icon{position:relative;display:grid;place-items:center;width:34px;height:100%;border:0;background:none;color:#f5f5f5;cursor:pointer;padding:0}.nav-icon svg{width:26px;height:26px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.nav-icon.active{color:#f15a24}.nav-icon i{position:absolute;top:13px;right:-5px;min-width:17px;height:17px;padding:0 4px;border-radius:99px;background:#f2ae17;color:#191919;font-size:.66rem;line-height:17px;font-style:normal}.nav-links-toggle{display:none}.account-control{position:relative;height:100%}.account-menu{position:absolute;right:0;top:57px;width:155px;padding:7px;background:#1b1b1d;border:1px solid #39393c;box-shadow:0 12px 28px rgba(0,0,0,.35)}.account-menu button{display:block;width:100%;padding:10px;border:0;background:none;color:#e6e6e6;text-align:left;cursor:pointer;font:inherit;font-size:.78rem}.account-menu button:hover{color:#f15a24}@media(max-width:900px){.nav{width:calc(100% - 20px);height:54px;gap:10px}.brand img{width:76px}.nav-links-toggle{display:grid;width:28px;flex:0 0 28px}.nav-links-toggle svg{width:19px;height:19px;stroke-width:1.5}.nav-links{position:absolute;top:100%;left:0;width:min(280px,calc(100% - 16px));height:auto;padding:10px 12px 14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:3px;background:#090909;border:1px solid #2b2b2d;box-shadow:0 15px 30px rgba(0,0,0,.4);opacity:0;visibility:hidden;transform:translateY(-8px);transition:opacity .18s ease,transform .18s ease,visibility .18s}.nav-links.open{opacity:1;visibility:visible;transform:translateY(0)}.nav-links button{height:auto;padding:12px 8px;text-align:left;font-size:.75rem}.account-menu{top:50px}}@media(max-width:430px){.nav{width:calc(100% - 16px);gap:7px}.brand img{width:67px}nav{gap:4px}.nav-icon{width:30px}}</style>
