<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import logo from '../../../assets/desktop/rawr-logo.png'
import bannerBg from '../../../assets/desktop/bannerbg.jpeg'
defineProps({page:String,cartCount:Number,signedIn:Boolean})
const emit=defineEmits(['navigate','logout']),links=[['home','HOME'],['shop','SHOP'],['ingredients','INGREDIENTS'],['about','ABOUT'],['reviews','REVIEWS'],['contact','CONTACT']],accountOpen=ref(false),accountControl=ref(null)
const account=()=>{if(!accountOpen.value) accountOpen.value=true}
const closeOnOutsideClick=event=>{if(accountControl.value&&!accountControl.value.contains(event.target))accountOpen.value=false}
onMounted(()=>document.addEventListener('click',closeOnOutsideClick))
onBeforeUnmount(()=>document.removeEventListener('click',closeOnOutsideClick))
</script>
<template><header :style="{backgroundImage:`linear-gradient(rgba(10, 11, 12, 0.50),rgba(10,11,12,.50)),url(${bannerBg})`}"><div class="wrap nav"><button class="brand" @click="emit('navigate','home')"><img :src="logo" alt="RAWR"></button><nav><button v-for="[id,label] in links" :key="id" :class="{active:page===id}" @click="emit('navigate',id)">{{label}}</button><button class="nav-icon cart-button" :class="{active:page==='cart'}" aria-label="Cart" @click="emit('navigate','cart')"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M2 4h4l3.2 16.2h15.4l3.4-11.3H8.1"/><circle cx="12" cy="26" r="1.8"/><circle cx="24" cy="26" r="1.8"/></svg><i v-if="cartCount">{{cartCount}}</i></button><div ref="accountControl" class="account-control"><button class="nav-icon" :class="{active:page==='account'}" :aria-expanded="accountOpen" aria-label="Account" @click="signedIn?account():emit('navigate','account')"><svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="10" r="5"/><path d="M6 28c1.1-6 4.6-9 10-9s8.9 3 10 9"/></svg></button><div v-if="signedIn&&accountOpen" class="account-menu"><button @click="accountOpen=false;emit('navigate','account')">Order history</button><button @click="accountOpen=false;emit('logout')">Log out</button></div></div></nav></div></header></template>
<style scoped>header{position:sticky;top:0;z-index:20;background-size:cover;background-position:center;border-bottom:1px solid #34302d}.nav{height:65px;display:flex;align-items:center;justify-content:space-between}.brand{border:0;background:none;padding:0;display:flex}.brand img{width:82px;height:82px;object-fit:contain}nav{display:flex;align-items:center;gap:14px;height:100%}nav>button:not(.nav-icon){position:relative;background:none;border:0;color:#d0d0d0;font-size:.83rem;letter-spacing:.1em;font-weight:800;cursor:pointer;padding:0;height:100%}nav>button:hover,nav>button.active{color:#fff}.nav-icon{position:relative;display:grid;place-items:center;width:34px;height:100%;border:0;background:none;color:#f5f5f5;cursor:pointer;padding:0}.nav-icon svg{width:26px;height:26px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.nav-icon.active{color:#f15a24}.nav-icon i{position:absolute;top:13px;right:-5px;min-width:17px;height:17px;padding:0 4px;border-radius:99px;background:#f2ae17;color:#191919;font-size:.66rem;line-height:17px;font-style:normal}.account-control{position:relative;height:100%}.account-menu{position:absolute;right:0;top:57px;width:155px;padding:7px;background:#1b1b1d;border:1px solid #39393c;box-shadow:0 12px 28px rgba(0,0,0,.35)}.account-menu button{display:block;width:100%;padding:10px;border:0;background:none;color:#e6e6e6;text-align:left;cursor:pointer;font:inherit;font-size:.78rem}.account-menu button:hover{color:#f15a24}@media(max-width:800px){.nav{height:70px;width:calc(100% - 20px)}.brand img{width:62px;height:62px}nav{gap:9px;overflow:visible}nav>button:not(.nav-icon){display:none}.nav-icon{width:30px}.nav-icon svg{width:24px;height:24px}}</style>
